-- Borrar Prototipo de zapatería
DROP DATABASE IF EXISTS PROT_ZAPATERIA;

-- Crear base de datos del prototipo zapateria
CREATE DATABASE PROT_ZAPATERIA;

-- Usar base de datos de la base de datos zapateria
USE PROT_ZAPATERIA;

-- Crear tabla usuario (Básico)
CREATE TABLE USUARIO(
	CODUSER		INT,
    USERNOM		VARCHAR(50),
    USERNAME	VARCHAR(50),
    CONSTRAINT PRIMARY KEY (CODUSER)
);

-- Insertar datos a la tabla (único usuario por el momento)
INSERT INTO USUARIO (CODUSER, USERNOM, USERNAME) VALUES (1, "frederic123@gmail.com", "Alfredo");

-- Mostrar contenido de la tabla Usuario
DESCRIBE USUARIO;

-- Crear tabla Usuario / Persona
CREATE TABLE CLIENTE(
	CODCLI		CHAR(4),
    NOMCLI		VARCHAR(50),
    APECLI		VARCHAR(50),
    CELCLI		CHAR(9),
    DNICLI		CHAR(8),
    FLG			CHAR(1) default 'A',
    CONSTRAINT CODCLI PRIMARY KEY (CODCLI)
);

-- Insertar datos a la tabla
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A001", "Marcos", "Lucas", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A002", "Tobías", "Berrocal", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A003", "Carlos", "Alcántara", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A004", "Sofía", "Reyero", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A005", "Rosa", "de las Mercedes", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A006", "Ysabel", "Caceres", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A007", "Matías", "Mateo", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A008", "Filomena", "Pichot", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A009", "Jesús", "de Nazaret", "123456789", "12345678", "A");
INSERT INTO CLIENTE (CODCLI, NOMCLI, APECLI, CELCLI, DNICLI, FLG) VALUES ("A010", "Jeff", "Jeffar", "123456789", "12345678", "A");

-- Mostrar tabla cliente
DESCRIBE CLIENTE;

-- Crear tabla Datos Producto
CREATE TABLE PRODUCTO(
	CODPRO		CHAR(4),
    CODUSER		INT,
    COLPRO		varchar(50),
    TALPRO		CHAR(2),
    PREPRO		DECIMAL(10,2),
    TIPPRO		VARCHAR(50),
    STOPRO		CHAR(4),
    CODMAR		CHAR(4),
    CONSTRAINT CODPRO PRIMARY KEY (CODPRO)
);

-- Insertar datos a la tabla
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B001", "32", 12.4, "Chancla");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B002", "32", 12.4, "Zapato");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B003", "32", 12.4, "Sandália");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B004", "32", 12.4, "Bota");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B005", "32", 12.4, "Tacones");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B006", "32", 12.4, "Crocks");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B007", "32", 12.4, "Pantufla");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B008", "32", 12.4, "Zapatilla");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B009", "32", 12.4, "Pantufla");
INSERT INTO PRODUCTO (CODPRO, TALPRO, PREPRO, TIPPRO) VALUES ("B010", "32", 12.4, "Tacones");

-- Mostrar tabla Producto
DESCRIBE PRODUCTO;

-- Crear tabla Venta
CREATE TABLE VENTA(
	CODVEN		CHAR(4),
    CODUSER	INT,
    FECVEN		DATE,
    CODCLI		CHAR(4),
    CONSTRAINT CODVEN PRIMARY KEY (CODVEN)
);

-- Insertar datos a la tabla
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C001", "2015/09/20");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C002", "1999/09/25");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C003", "2010/10/15");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C004", "2017/08/06");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C005", "3026/08/05");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C006", "2030/02/28");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C007", "2036/07/20");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C008", "2015/09/20");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C009", "2040/03/22");
INSERT INTO VENTA (CODVEN, FECVEN) VALUES ("C010", "2060/11/11");

-- Mostrar tabla Venta
DESCRIBE VENTA;

-- Crear tabla Marca
CREATE TABLE MARCA(
	CODMAR		CHAR(4),
    NOMMAR		VARCHAR(10),
    CONSTRAINT CODMAR PRIMARY KEY (CODMAR)
);

-- Ingresar datos en la tabla Marca
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J001", "NIKE");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J002", "PUMA");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J003", "ADDIDAS");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J004", "CALZADITO");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J005", "Suelín");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J006", "NIKEA");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J007", "GUEPARDO");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J008", "EDIDAS");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J009", "BOTÍNCAT");
INSERT INTO MARCA (CODMAR, NOMMAR) VALUES ("J010", "CATERPILAR");

-- Mostrar tabla Marca
DESCRIBE MARCA;

-- Crear tabla Venta Detalle
CREATE TABLE VENTADETALLE(
	CODVENDET		CHAR(4),
    CANVENDET		INT,
    CODPRO			CHAR(4),
    CODVEN			CHAR(4),
    CONSTRAINT CODVENDET PRIMARY KEY(CODVENDET)
);

-- Insertar datos a la tabla venta detalle
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D001", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D002", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D003", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D004", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D005", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D006", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D007", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D008", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D009", 20);
INSERT INTO VENTADETALLE (CODVENDET, CANVENDET) VALUES ("D010", 20);

-- Mostrar tabla Venta Detalle
DESCRIBE VENTADETALLE;


-- Relacion entre tablas Venta - Venta Detalle
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTA_VENTADETALLE_CODVENDET FOREIGN KEY (CODVEN) REFERENCES VENTA(CODVEN);

-- Relacion entre las tablas Producto - Marca
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_MARCA_CODMAR FOREIGN KEY (CODMAR) REFERENCES MARCA(CODMAR);

-- Relación entre las tablas Producto - Persona
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_USUARIO_CODUSER FOREIGN KEY(CODUSER) REFERENCES USUARIO(CODUSER);

-- Relación entre las tablas Venta - Persona
ALTER TABLE VENTA ADD CONSTRAINT VENTA_USUARIO_CODUSER FOREIGN KEY (CODUSER) REFERENCES USUARIO(CODUSER);

-- Relación entre las tablas Venta_Detalle - Producto
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLA_PRODUCTO_CODPRO FOREIGN KEY (CODPRO) REFERENCES PRODUCTO(CODPRO);